"""initial migration

Revision ID: 8782364a6401
Revises: 
Create Date: 2018-06-28 18:55:30.638765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8782364a6401'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chanpins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pinming', sa.String(length=64), nullable=True),
    sa.Column('jiage', sa.Float(), nullable=True),
    sa.Column('beizhu', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chanpinxxs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pinming', sa.String(length=64), nullable=True),
    sa.Column('chanshux', sa.String(length=64), nullable=True),
    sa.Column('chanshuz', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('pin', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('tel', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('isuse', sa.Boolean(), nullable=True),
    sa.Column('beizhu', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user'), 'users', ['user'], unique=True)
    op.create_table('xiaoqus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xiaoqu', sa.String(length=64), nullable=True),
    sa.Column('dizhi', sa.String(length=100), nullable=True),
    sa.Column('beizhu', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xiaoqus_xiaoqu'), 'xiaoqus', ['xiaoqu'], unique=True)
    op.create_table('kehus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('xiaoqu_id', sa.Integer(), nullable=True),
    sa.Column('fangjian', sa.String(length=64), nullable=True),
    sa.Column('chenghu', sa.String(length=64), nullable=True),
    sa.Column('tel', sa.String(length=64), nullable=True),
    sa.Column('zje', sa.Float(), nullable=True),
    sa.Column('beizhu', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('time0', sa.DateTime(), nullable=True),
    sa.Column('time1', sa.DateTime(), nullable=True),
    sa.Column('time2', sa.DateTime(), nullable=True),
    sa.Column('time3', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['xiaoqu_id'], ['xiaoqus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dingdans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kehu_id', sa.Integer(), nullable=True),
    sa.Column('chanpin_id', sa.Integer(), nullable=True),
    sa.Column('shuliang', sa.Integer(), nullable=True),
    sa.Column('weizhi', sa.String(length=64), nullable=True),
    sa.Column('xinghao', sa.String(length=64), nullable=True),
    sa.Column('kuan_chang', sa.Integer(), nullable=True),
    sa.Column('gao', sa.Integer(), nullable=True),
    sa.Column('meikongkuan_bashoudigao', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('shanshu', sa.Integer(), nullable=True),
    sa.Column('zhonghengtiaoshu_gantiaoshu', sa.Integer(), nullable=True),
    sa.Column('shuowei', sa.String(length=64), nullable=True),
    sa.Column('ishaveht', sa.String(length=64), nullable=True),
    sa.Column('zhangfa_dengfenshu_kaishuofangshi', sa.String(length=64), nullable=True),
    sa.Column('jiage', sa.Float(), nullable=True),
    sa.Column('tushipic', sa.String(length=64), nullable=True),
    sa.Column('beizhu', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('fakaidi', sa.String(length=64), nullable=True),
    sa.Column('time0', sa.DateTime(), nullable=True),
    sa.Column('user0_id', sa.Integer(), nullable=True),
    sa.Column('time1', sa.DateTime(), nullable=True),
    sa.Column('user1_id', sa.Integer(), nullable=True),
    sa.Column('time2', sa.DateTime(), nullable=True),
    sa.Column('user2_id', sa.Integer(), nullable=True),
    sa.Column('time3', sa.DateTime(), nullable=True),
    sa.Column('user3_id', sa.Integer(), nullable=True),
    sa.Column('time4', sa.DateTime(), nullable=True),
    sa.Column('user4_id', sa.Integer(), nullable=True),
    sa.Column('time5', sa.DateTime(), nullable=True),
    sa.Column('user5_id', sa.Integer(), nullable=True),
    sa.Column('time6', sa.DateTime(), nullable=True),
    sa.Column('user6_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chanpin_id'], ['chanpins.id'], ),
    sa.ForeignKeyConstraint(['kehu_id'], ['kehus.id'], ),
    sa.ForeignKeyConstraint(['user0_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user3_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user4_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user5_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user6_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dingdans')
    op.drop_table('kehus')
    op.drop_index(op.f('ix_xiaoqus_xiaoqu'), table_name='xiaoqus')
    op.drop_table('xiaoqus')
    op.drop_index(op.f('ix_users_user'), table_name='users')
    op.drop_table('users')
    op.drop_table('chanpinxxs')
    op.drop_table('chanpins')
    # ### end Alembic commands ###
