"""empty message

Revision ID: 8c40cca5964b
Revises: 
Create Date: 2018-06-16 11:56:59.192624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c40cca5964b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chanpins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pinming', sa.String(length=64), nullable=True),
    sa.Column('danjia', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('pin', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('isuse', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user'), 'users', ['user'], unique=True)
    op.create_table('xiaoqus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xiaoqu', sa.String(length=64), nullable=True),
    sa.Column('weizhi', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xiaoqus_xiaoqu'), 'xiaoqus', ['xiaoqu'], unique=True)
    op.create_table('kehus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donghao', sa.String(length=64), nullable=True),
    sa.Column('fanghao', sa.String(length=64), nullable=True),
    sa.Column('chenghu', sa.String(length=64), nullable=True),
    sa.Column('tel', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('xdtime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('xiaoqu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['xiaoqu_id'], ['xiaoqus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dingdans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shuliang', sa.Integer(), nullable=True),
    sa.Column('weizhi', sa.String(length=64), nullable=True),
    sa.Column('xinghao', sa.String(length=64), nullable=True),
    sa.Column('kuan_chang', sa.Integer(), nullable=True),
    sa.Column('gao', sa.Integer(), nullable=True),
    sa.Column('meikuan_digao', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('shanshu', sa.Integer(), nullable=True),
    sa.Column('zhonghengtiaoshu_gantiaoshu', sa.Integer(), nullable=True),
    sa.Column('shuowei', sa.String(length=64), nullable=True),
    sa.Column('zhangfa', sa.String(length=64), nullable=True),
    sa.Column('ishaveht', sa.Boolean(), nullable=True),
    sa.Column('dengfenshu', sa.String(length=64), nullable=True),
    sa.Column('danjia', sa.Float(), nullable=True),
    sa.Column('tushipic', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('fakaidi', sa.String(length=64), nullable=True),
    sa.Column('fahuotime', sa.DateTime(), nullable=True),
    sa.Column('kehu_id', sa.Integer(), nullable=True),
    sa.Column('chanpin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chanpin_id'], ['chanpins.id'], ),
    sa.ForeignKeyConstraint(['kehu_id'], ['kehus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dingdans')
    op.drop_table('kehus')
    op.drop_index(op.f('ix_xiaoqus_xiaoqu'), table_name='xiaoqus')
    op.drop_table('xiaoqus')
    op.drop_index(op.f('ix_users_user'), table_name='users')
    op.drop_table('users')
    op.drop_table('chanpins')
    # ### end Alembic commands ###
